plugins {
    id 'java'
    id("io.qameta.allure") version "$qameta_allure_version"
    id 'jacoco'
    id 'checkstyle'
    id 'maven-publish'
}

group 'my.important.job'
version '1.0'

ext {
    nexusUrl = System.getenv("NEXUS_URL") ?: project.findProperty("nexus_url")
    nexusUsername = System.getenv("NEXUS_USERNAME") ?: project.findProperty("nexus_user")
    nexusPassword = System.getenv("NEXUS_PASSWORD") ?: project.findProperty("nexus_password")

    junitJupiter = "org.junit.jupiter:junit-jupiter-api:$junit_jupiter_version"
    junitJunit5 = "org.junit.jupiter:junit-jupiter-engine:$allure_junit5_version"

    postgres = "org.postgresql:postgresql:$postgresql_version"
}

repositories {
    mavenCentral()
//    maven {
//        allowInsecureProtocol = true
//        url = "${nexusUrl}${nexus_maven_central}"
//        credentials {
//            username nexusUsername
//            password nexusPassword
//        }
//    }
//    maven {
//        allowInsecureProtocol = true
//        url = "${nexusUrl}${nexus_maven_releases}"
//        credentials {
//            username nexusUsername
//            password nexusPassword
//        }
//    }
//    maven {
//        allowInsecureProtocol = true
//        url = "${nexusUrl}${nexus_maven_snapshots}"
//        credentials {
//            username nexusUsername
//            password nexusPassword
//        }
//    }
}

dependencies {
    implementation 'org.eclipse.jetty:jetty-server:12.1.5'
    implementation 'org.eclipse.jetty.ee10:jetty-ee10-servlet:12.1.5'

    implementation 'org.glassfish.jersey.core:jersey-server:3.1.11'
    implementation 'org.glassfish.jersey.containers:jersey-container-servlet-core:3.1.11'
    implementation 'org.glassfish.jersey.media:jersey-media-json-jackson:3.1.11'
    implementation 'org.glassfish.jersey.inject:jersey-hk2:3.1.11'

    implementation 'ch.qos.logback:logback-classic:1.5.21'

    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.20.1'

    testImplementation "${junitJupiter}"
    testRuntimeOnly "${junitJupiter}"
    testImplementation "${junitJunit5}"
    implementation "${postgres}"
}

checkstyle {
    toolVersion='10.12.4'
    configFile = file("config/checkstyle/checkstyle.xml")
}

jacoco {
    toolVersion = "${jacoco_version}"
}

jacocoTestReport {
    reports {
        xml.required.set(false)
        html.required.set(true)
        csv.required.set(false)
    }
    dependsOn test
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.80
            }
        }
    }
    dependsOn test
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            group group
            artifactId 'haydar_test'
            version version
        }
    }
    repositories {
        maven {
            allowInsecureProtocol = true
            url = version.endsWith("SNAPSHOT") ? "${nexusUrl}${nexus_maven_snapshots}" : "${nexusUrl}${nexus_maven_releases}"
            credentials {
                username nexusUsername
                password nexusPassword
            }
        }
    }
}